### ISSUE TITLE
[Tripal 3] Field rendering issues

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_interpro#24] opened 2019-01-17 10:52 UTC
Hello,

I'm having trouble with the field showing the interpro graphs.

On both Firefox and Chrome, by default the graph is empty, until the window is resized

![image](https://user-images.githubusercontent.com/17642511/51313489-f8c56200-1a4d-11e9-82a2-c4021a7fe1cb.png)

After resizing

![image](https://user-images.githubusercontent.com/17642511/51313529-15619a00-1a4e-11e9-9ac6-c0209a264f48.png)

Though on Firefox, only part of the graph actually appears : 

![image](https://user-images.githubusercontent.com/17642511/51313575-332eff00-1a4e-11e9-9ff6-d13fe59c1260.png)

I remember Firefox being finicky with svg with might be the cause of the issue.

**Comment by bradfordcondon** [comment] 2019-01-17 14:54
I had this same problem.  Can you double check that you have jquery update enabled: https://www.drupal.org/project/jquery_update

**Comment by mboudet** [comment] 2019-01-17 15:02
Yes, it's enabled (required by tripal_analysis_expression).

**Comment by almasaeed2010** [comment] 2019-01-17 16:12
To fix this issue we have to trigger an event in the js after the pane has completed it's transition from hidden to visible. I'll make a PR to fix this.

**Comment by almasaeed2010** [comment] 2019-01-17 16:56
Looking at the code. I think this should be fixed on core since it implements tripal_ds. I'll open an issue there.

**Comment by almasaeed2010** [comment] 2019-01-17 17:14
A PR submitted for this here: https://github.com/tripal/tripal/pull/825

**Comment by bradfordcondon** [comment] 2019-01-24 16:43
this has been merged on core.  If you update tripal you should see this issue resolved.

thanks for bringing it up, thanks for fixing it :D

**Comment by kyrenya** [comment] 2019-01-24 17:12
hi! I just updated (with drush updatedb), but still having issues with the visualisation... 
![image](https://user-images.githubusercontent.com/43243429/51695169-4c115480-1ffa-11e9-9bd2-7f0a1bb6b369.png)
and issue not solved apparently..
![image](https://user-images.githubusercontent.com/43243429/51695516-29337000-1ffb-11e9-8264-f48ba345e1b8.png)

any ideas of what can I be doing wrong? Thx!

**Comment by bradfordcondon** [comment] 2019-01-24 17:17
please try `drush cc all`

and you've also run `git pull` on the core tripal repository, with your `git log` showing the last commit was  `bb35a1457857e47f3c0e79a8508e8edaa0b297f4`?

**Comment by mboudet** [comment] 2019-01-24 17:22
I have the same issue. The problem was twofold : the resize issue on all browsers, and the graph issue (graphs only works on chrome..)

The graph is made the exact same way as in tripal v2 I believe? It could be that the svg is not properly sized for the panel, and thus the browser refuse to render it? I think svg rendering is pretty browser-dependant, but I could be wrong.

At least is works fine on chrome for now.

**Comment by bradfordcondon** [comment] 2019-01-24 17:27
i've only tested on chrome...
the graph is made with the featureviewer library https://github.com/calipho-sib/feature-viewer which yes is SVG i think.

thanks for confirming the fix worked for you on chrome.  It's failing for you on a different browser?

**Comment by mboudet** [comment] 2019-01-25 08:29
Well, it fails for me on Firefox, Internet explorer, and Edge. I did not try any other browser.

**Comment by kyrenya** [comment] 2019-01-25 09:30
uhmm.. I made git pull but with git log this is my last commit.. 
![image](https://user-images.githubusercontent.com/43243429/51737146-cd60f980-2083-11e9-9023-f2ed86d97fc6.png)

**Comment by kyrenya** [comment] 2019-01-25 09:35
I updated drupal (to 7.63), and now I see properly the alignments in Chromium in Ubuntu, 
but nothing in mozilla (not even resizing window).

**Comment by mboudet** [comment] 2019-01-25 12:45
Ok, there seems to be an issue with the "clip-path" part of the rectangle. Removing it makes the lines appears again. I'm looking into it.

**Comment by bradfordcondon** [comment] 2019-01-25 12:59
>uhmm.. I made git pull but with git log this is my last commit..

are you on the right branch `7.x-3.x`?

>Ok, there seems to be an issue with the "clip-path" part of the rectangle.

i've always noticed a lot of "negative value" svg complaints.    We're also on v0.1.44 of featureviewer, where theres been a 1.0.4 release: lets try upgrading featureviewer and seeing if that works...

**Comment by mboudet** [comment] 2019-01-25 13:01
Ok, "found" (-ish) the issue.
In the graph, we have several "clip-path="url(#clip)".
It refers to a clipPath element, generated by feature-viewer.

The issue is this : this clipPath element have these dimensions : "rect width="-147" height="570""

Obviously, 'rect width="-147"' is an issue. Google Chrome actually shows it as an error, and ignore the instruction, thus printing it. Manually setting it to a proper value makes the lines appears.

![image](https://user-images.githubusercontent.com/17642511/51747296-5a6a7980-20a9-11e9-84cd-829727d170fc.png)

The issue stems from the resize of the element I guess? Since when the panel is not actually selected, its width is negative, the #clip element is set with a negative width too. But it's not resized afterward.

I did not see it before, but the tripal_analysis_blast have the same issue.

**Comment by mboudet** [comment] 2019-01-25 13:05
Also, the "sequence" line is not filled, not matter the browser. (But it might be a separate issue).

**Comment by mboudet** [comment] 2019-01-25 13:07
> i've always noticed a lot of "negative value" svg complaints. We're also on v0.1.44 of featureviewer, where theres been a 1.0.4 release: lets try upgrading featureviewer and seeing if that works...

I'm not sure it would fix it. I think the #clip size is generated with the page, and thus set to negative since the div container is in negative too.

**Comment by bradfordcondon** [comment] 2019-01-25 13:24
>Also, the "sequence" line is not filled, not matter the browser. (But it might be a separate issue).

have you tried zooming in ( a lot?) the sequence displays there but only at a high magnification
![screen shot 2019-01-25 at 8 24 39 am](https://user-images.githubusercontent.com/7063154/51748523-aeaa3500-207a-11e9-97f3-1877b6d35e8e.png)

![screen shot 2019-01-25 at 8 24 06 am](https://user-images.githubusercontent.com/7063154/51748503-a225dc80-207a-11e9-9af7-100beb091b8b.png)

**Comment by mboudet** [comment] 2019-01-25 13:26
Oh, you're right! No issue there then

**Comment by bradfordcondon** [comment] 2019-01-25 14:17
>I'm not sure it would fix it. I think the #clip size is generated with the page, and thus set to negative since the div container is in negative too.

youre right, upgrading had no effect.

i've confirmed i still have this issue on safari, so i'll bring it back to the core issue and see if we can work it out.

**Comment by mboudet** [comment] 2019-01-25 14:29
It would be easier if the #clip object used a % value for it's height and width, instead of a size.
Since it's not reacting to a resize (but its container is), I'm not sure what can be done.

**Comment by bradfordcondon** [comment] 2019-01-25 14:40
ok, i got it to draw on safari.  just needed to update the version to 1.0.4

```
 drupal_add_js("https://cdn.rawgit.com/calipho-sib/feature-viewer/v1.0.4/dist/feature-viewer.bundle.js", array(
      'type' => 'external',
      'scope' => 'header',
      'group' => 15,
      'every_page' => TRUE,
      'weight' => 400,
    ));
```

**Comment by mboudet** [comment] 2019-01-25 14:44
Perfect! I was actually looking at the source code of the lib.
We can even use the minified version.
(https://cdn.rawgit.com/calipho-sib/feature-viewer/v1.0.4/dist/feature-viewer.min.js)
It works fine with my install.

**Comment by bradfordcondon** [comment] 2019-01-25 14:45
i made a pr on branch `upgrade_feature_viewer` if you all want to check it out and confirm this fixes the issue for you

**Comment by mboudet** [comment] 2019-01-25 14:50
Works perfectly .
![image](https://user-images.githubusercontent.com/17642511/51752835-ac66cb80-20b8-11e9-91db-81f26171aa21.png)

You can probably make the same PR for tripal_analysis_blast, it should fix the problem there too.

Thanks!

**Closed as completed** 2019-02-05 03:39 UTC
Labels: bug, question

**Comment by kyrenya** [comment] 2019-02-05 17:50
sorry! I didnt get back to this until now.. I updated with git pull and now it works! 
thanks so much both!

**Comment by kyrenya** [comment] 2019-02-05 18:22
oops, false alarm, it works for me now in blast alignments, but still doesnt work for interpro results.
I'm talking about firefox in ubuntu, anyone tested it in this particular case?

**Comment by mboudet** [comment] 2019-02-08 10:30
Sorry, I only tested on window. Does it appears when resizing, or not at all?

**Comment by kyrenya** [comment] 2019-02-08 10:39
not at all!
